github:
  is_project_page: false

plugins:
  - jekyll-include-cache

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast"


title: Scrum.COM.TW
description: [å°±åƒæ˜¯ç©ç±ƒçƒğŸ€ æœ‰ç±ƒçƒè¦å‰‡ï¼Œã€Scrumã€‘ä¹Ÿæœ‰è‡ªå·±çš„å®šç¾©ï¼]
show_downloads: false
google_analytics: UA-177167416-2

