github:
  is_project_page: false

theme: jekyll-theme-cayman

title: [ä»€éº¼æ˜¯ Scrumï¼Ÿ]
description: [å°±åƒæ˜¯ç©ç±ƒçƒğŸ€ æœ‰ç±ƒçƒè¦å‰‡ï¼Œã€Scrumã€‘ä¹Ÿæœ‰è‡ªå·±çš„å®šç¾©ï¼]
show_downloads: false
google_analytics: UA-177167416-2

